packages:
  - 'src/common/leafer'
  - 'src/common/leafer/packages/*'
  - 'src/common/leafer/packages/platform/*'
  - 'src/common/leafer/packages/display-module/*'
  - 'src/common/leafer/packages/canvas/*'
  - 'src/common/leafer/packages/image/*'
  - 'src/common/leafer/packages/partner/*'
  - 'src/common/ui'
  - 'src/common/ui/packages/*'
  - 'src/common/ui/packages/core/*'
  - 'src/common/ui/packages/platform/*'
  - 'src/common/ui/packages/display-module/*'
  - 'src/common/ui/packages/interaction/*'
  - 'src/common/ui/packages/partner/*'
  - 'src/common/in'
  - 'src/common/in/packages/*'
  - 'src/common/draw'
  - 'src/common/draw/packages/*'
  - 'src/common/draw/packages/platform/*'
  - 'src/common/editor'
  - 'src/common/editor/packages/*'
  - 'src/common/editor/packages/platform/*'
  - 'src/common/game'
  - 'src/common/game/packages/*'
  - 'src/common/game/packages/platform/*'
